cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('order.urls',namespace='order')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('',include('shop.urls',namespace='shop')),
    path('rest_shop/',include('rest_shop.urls',namespace='rest_shop')),
    path('rest_order/',include('rest_order.urls',namespace='rest_order')),
    path('rest_cart/',include('rest_cart.urls',namespace='rest_cart')),
]

urlpatterns+= static (settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/products/',views.product_list,name='products'),
    path('<slug:category_slug>/',views.product_list,name='products_by_category'),
    path('<int:product_id>/<slug:slug>/',views.product_detail,name='product_detail'),
]

templates/base.html
{% load static %}
{% load bootstrap5 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <div class="container">
    <div class="page-header">
        <a href="{% url 'shop:products' %}"><h1>My shop</h1></a>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            {# call __len__ #}
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart:
                    <a href="{% url "cart:cart_detail" %}">
                        {# If total_items is 1, the output will be 1 item. #}
                        {# If total_items is 2, the output will be 2 items. #}
                        {{ total_items }} item{{ total_items|pluralize }},
                        ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your shopping cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div> 
    <div>
        {% block content %}{% endblock content %}   

    </div>
</body>
</html>