cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('order.urls',namespace='order')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('',include('shop.urls',namespace='shop')),
    path('rest_shop/',include('rest_shop.urls',namespace='rest_shop')),
    path('rest_order/',include('rest_order.urls',namespace='rest_order')),
    path('rest_cart/',include('rest_cart.urls',namespace='rest_cart')),
]

urlpatterns+= static (settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views


app_name = 'payment'

urlpatterns = [
    path('process/',views.payment_process,name='process'),
    path('done/',views.payment_done,name='done'),
    path('canceled/',views.payment_canceled,name='canceled'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/products/',views.product_list,name='products'),
    path('<slug:category_slug>/',views.product_list,name='products_by_category'),
    path('<int:product_id>/<slug:slug>/',views.product_detail,name='product_detail'),
]

payment/views.py
from django.shortcuts import render , get_object_or_404
from decimal import Decimal
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from order.models import Order
# Create your views here.


def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order,id=order_id)
    host = request.get.host()
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': '%.2f' % order.get_total_cost().quantize(
            Decimal('.01')),
        'item_name': f'Order {order.id}',
        'invoice': str(order.id),
        'currency_code': 'USD',
        'notify_url': 'http://{}{}'.format(host,
                                           reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,
                                           reverse('payment:done')),
        'cancel_return': 'http://{}{}'.format(host,
                                              reverse('payment:canceled')),
    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request,
                  'payment/process.html',
                  {'order': order, 'form': form})

@csrf_exempt
def payment_done(request):
    return render(request,'payment/done.html')

@csrf_exempt
def payment_canceled(request):
    return render(request,'payment/cancell.html')

templates/payment/cancell.html
{% extends "base.html" %}
{% block content %}
    <h1>Your payment has not been processed</h1><hr>
    <p>There was a problem processing your payment 🥲 .</p>
    <div>
        <a href="{% url 'payment:process' %}">Click here</a>
    </div>
{% endblock %}

templates/payment/done.html
{% extends 'base.html' %}

{% block title %} Successful payment {% endblock title %}  

{% block content %}

    <h1>Your payment has been successfuly</h1>
    <p>Be Happy with Smile 😍 </p>

    <div>
        <a href="{% url 'shop:products' %}"><button type="submit">Back to Home</button></a>
    </div>

{% endblock content %}

    

templates/payment/process.html
{% extends 'base.html' %}
{% block title %}
    
    Pay Using Paypal

{% endblock title %}
    
{% block content %}

    <h1>Pay Using Paypal</h1>
    <hr>
    {{form.render}}

{% endblock content %}

    


    